### ISSUE TITLE
Null pointer Exception

### ISSUE THREAD

**Issue by athirasanthosh** [qs-lll/ExpandingPager#9]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qslll.expandingpager/com.qslll.expandingpager.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setAdapter(android.support.v4.view.PagerAdapter)' on a null object reference
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setAdapter(android.support.v4.view.PagerAdapter)' on a null object reference
                                                                              at com.qslll.expandingpager.MainActivity.onCreate(MainActivity.java:42)
                                                                              at android.app.Activity.performCreate(Activity.java:6010)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by qs-lll** [comment]
maybe viewPager be null  :)
